"""Дз"""
#1)
name = input("Enter your name: ")
print("Hello,",name,"!")
#2)
one = int(input("Enter a number: "))
two = int(input("Enter another number: "))
print(two,",",one)
#3)
radius = int(input("Enter the radius: "))
print(radius * radius * 3.14)
#4)
celsius = int(input("Enter the degrees celsius: "))
print(celsius * 9/5 + 32)
#5)
price = int(input("Enter the price: "))
discount = int(input("Enter your discount: "))
print(price / discount * 100)
#6)
number = int(input("Enter number A: "))
nomber = int(input("Enter number B: "))
print(nomber/number)
#7)ki
a = int(input("Enter number A: "))
b = int(input("Enter number B: "))
c = int(input("Enter number C: "))
#8)
"?"
#9)
diameter = int(input(" Enter the diameter: "))
print(diameter/2*diameter/2*3.14)
#10)
rodius = int(input("Enter the radius: "))
height = int(input("Enter the height: "))
print(rodius * rodius * 3.14 * height)